export {
  CANONICAL_ID_WORDS,
  ENTITY_ID_TYPES,
  LEGACY_OBSERVATION_ID_WORDS,
  generateCanonicalId,
  generateHookId,
  generateObservationId,
  generateRunId,
  generateSuiteId,
  generateTestId,
  getEntityIdContract,
  getEntityIdContracts,
  isCanonicalId,
  isCanonicalHookId,
  isCanonicalObservationId,
  isCanonicalRunId,
  isCanonicalSuiteId,
  isCanonicalTestId,
  isObservationId,
  type EntityIdContract,
  type EntityIdType,
} from './persistent-id.js'

export {
  type ApprovedSaasPlaceholder,
  APPROVED_SAAS_PLACEHOLDERS,
  APPROVED_SAAS_PLACEHOLDER_NAMES,
  APPROVED_SAAS_PLACEHOLDER_SLUGS,
  selectApprovedSaasPlaceholder,
  selectApprovedSaasPlaceholderSlug,
} from './product-placeholders.js'
