export { WebPlatformAdapter } from './adapter.js'
export { FarmWebAdapter } from './farm-adapter.js'
export { observePage, parseAriaSnapshot } from './observer.js'
export { ElementResolver } from './element-resolver.js'
export { validateAction, ActionValidationError } from './action-validator.js'
export { waitForPageReady } from './smart-wait.js'
export type { ValidationResult } from './action-validator.js'
export type { SmartWaitOptions } from './smart-wait.js'
export type { RefMap, WebAdapterConfig, SnapshotResult } from './types.js'
export { runAccessibilityCheck, type AccessibilityOptions } from './accessibility.js'
export { extractDom } from './dom-extractor.js'
export type { ExtractDomOptions } from './dom-extractor.js'
