import * as monaco from 'monaco-editor'

export function registerThemes() {
  monaco.editor.defineTheme('agent-qa-dark', {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: 'f5f5f4', background: '1c1c1e' },
      { token: 'comment', foreground: '8f8f8f', fontStyle: 'italic' },
      { token: 'type', foreground: '5db8b5' },
      { token: 'type.yaml', foreground: '5db8b5' },
      { token: 'string', foreground: 'c4a46c' },
      { token: 'string.yaml', foreground: 'c4a46c' },
      { token: 'number', foreground: 'e8b868' },
      { token: 'number.yaml', foreground: 'e8b868' },
      { token: 'keyword', foreground: 'b8e4e2' },
      { token: 'tag', foreground: 'b8e4e2' },
      { token: 'tag.yaml', foreground: 'b8e4e2' },
      { token: 'operators.yaml', foreground: '8f8f8f' },
      { token: 'delimiter', foreground: '8f8f8f' },
      { token: 'constant.language', foreground: 'e8b868' },
    ],
    colors: {
      'editor.background': '#1c1c1e',
      'editor.foreground': '#f5f5f4',
      'editor.lineHighlightBackground': '#262626',
      'editor.selectionBackground': '#2b2b2d',
      'editor.inactiveSelectionBackground': '#2b2b2d80',
      'editorCursor.foreground': '#4fc6c3',
      'editorLineNumber.foreground': '#8f8f8f',
      'editorLineNumber.activeForeground': '#b0b0b0',
      'editorIndentGuide.background': '#2b2b2d',
      'editorIndentGuide.activeBackground': '#3a3a3a',
      'editorGutter.background': '#1c1c1e',
      'editor.selectionHighlightBackground': '#2b2b2d60',
      'editorBracketMatch.background': '#2b2b2d',
      'editorBracketMatch.border': '#3a3a3a',
      'editorWidget.background': '#262626',
      'editorWidget.border': '#2b2b2d',
      'editorSuggestWidget.background': '#262626',
      'editorSuggestWidget.border': '#2b2b2d',
      'editorSuggestWidget.selectedBackground': '#2b2b2d',
      'editorSuggestWidget.highlightForeground': '#4fc6c3',
      'editorHoverWidget.background': '#262626',
      'editorHoverWidget.border': '#2b2b2d',
      'editorOverviewRuler.border': '#2b2b2d',
      'scrollbarSlider.background': '#2b2b2d80',
      'scrollbarSlider.hoverBackground': '#3a3a3a80',
      'scrollbarSlider.activeBackground': '#8f8f8f80',
    },
  })

  monaco.editor.defineTheme('agent-qa-light', {
    base: 'vs',
    inherit: true,
    rules: [
      { token: '', foreground: '1c1c1e', background: 'fafaf9' },
      { token: 'comment', foreground: '737373', fontStyle: 'italic' },
      { token: 'type', foreground: '2f7d7a' },
      { token: 'type.yaml', foreground: '2f7d7a' },
      { token: 'string', foreground: '9a6f30' },
      { token: 'string.yaml', foreground: '9a6f30' },
      { token: 'number', foreground: 'd97706' },
      { token: 'number.yaml', foreground: 'd97706' },
      { token: 'keyword', foreground: '3a9996' },
      { token: 'tag', foreground: '3a9996' },
      { token: 'tag.yaml', foreground: '3a9996' },
      { token: 'operators.yaml', foreground: '737373' },
      { token: 'delimiter', foreground: '737373' },
      { token: 'constant.language', foreground: 'd97706' },
    ],
    colors: {
      'editor.background': '#fafaf9',
      'editor.foreground': '#1c1c1e',
      'editor.lineHighlightBackground': '#fdfdfc',
      'editor.selectionBackground': '#e8e8e6',
      'editor.inactiveSelectionBackground': '#e8e8e680',
      'editorCursor.foreground': '#3a9996',
      'editorLineNumber.foreground': '#737373',
      'editorLineNumber.activeForeground': '#525252',
      'editorIndentGuide.background': '#e8e8e6',
      'editorIndentGuide.activeBackground': '#d4d4d2',
      'editorGutter.background': '#fafaf9',
      'editor.selectionHighlightBackground': '#e8e8e660',
      'editorBracketMatch.background': '#e8e8e6',
      'editorBracketMatch.border': '#d4d4d2',
      'editorWidget.background': '#fafaf9',
      'editorWidget.border': '#e8e8e6',
      'editorSuggestWidget.background': '#fafaf9',
      'editorSuggestWidget.border': '#e8e8e6',
      'editorSuggestWidget.selectedBackground': '#fdfdfc',
      'editorSuggestWidget.highlightForeground': '#3a9996',
      'editorHoverWidget.background': '#fafaf9',
      'editorHoverWidget.border': '#e8e8e6',
      'editorOverviewRuler.border': '#e8e8e6',
      'scrollbarSlider.background': '#e8e8e680',
      'scrollbarSlider.hoverBackground': '#d4d4d280',
      'scrollbarSlider.activeBackground': '#73737380',
    },
  })
}
