export const SCHEMA_VERSION = 1

export interface DashboardMigration {
  version: number
  sql: string[]
}

export const MIGRATIONS: DashboardMigration[] = [
  {
    version: 1,
    sql: [
      `CREATE TABLE IF NOT EXISTS runs (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        file_path TEXT,
        status TEXT NOT NULL CHECK(status IN ('passed','failed','skipped','running','cancelled','pending','flaky')),
        priority INTEGER NOT NULL DEFAULT 0,
        duration INTEGER NOT NULL DEFAULT 0,
        attributes TEXT NOT NULL DEFAULT '{}',
        environment TEXT,
        metadata TEXT,
        started_at TEXT,
        ended_at TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        video_path TEXT,
        failure_summary TEXT,
        platform TEXT DEFAULT 'web',
        test_file_content TEXT,
        model_name TEXT,
        llm_provider TEXT,
        parallel INTEGER DEFAULT 0,
        parent_run_id TEXT,
        attempt_number INTEGER DEFAULT 0,
        retry_count INTEGER DEFAULT 0,
        max_retries INTEGER DEFAULT 0,
        error_log TEXT,
        memory_log TEXT,
        test_id TEXT,
        suite_id TEXT
      )`,
      `CREATE TABLE IF NOT EXISTS steps (
        id TEXT PRIMARY KEY,
        run_id TEXT NOT NULL REFERENCES runs(id),
        name TEXT NOT NULL,
        status TEXT NOT NULL CHECK(status IN ('passed','failed','healed','skipped','cancelled')),
        duration INTEGER NOT NULL DEFAULT 0,
        action TEXT,
        observation TEXT,
        reasoning TEXT,
        planned_action TEXT,
        result TEXT CHECK(result IN ('success','failure')),
        error TEXT,
        screenshot_path TEXT,
        screenshot_before_path TEXT,
        healing_attempts TEXT,
        retry_count INTEGER DEFAULT 0,
        captured_variables TEXT,
        step_order INTEGER NOT NULL DEFAULT 0,
        annotation_data TEXT,
        healing_screenshot_paths TEXT,
        accessibility_violations TEXT,
        confidence REAL,
        prompt_tokens INTEGER DEFAULT 0,
        completion_tokens INTEGER DEFAULT 0,
        total_tokens INTEGER DEFAULT 0,
        sub_actions_data TEXT,
        console_logs TEXT,
        network_logs TEXT,
        variable_snapshot TEXT,
        original_step_name TEXT,
        screen_context_before TEXT,
        screen_context_after TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE TABLE IF NOT EXISTS reasoning_traces (
        id TEXT PRIMARY KEY,
        step_id TEXT NOT NULL REFERENCES steps(id),
        observe_text TEXT,
        observe_duration INTEGER,
        plan_reasoning TEXT,
        plan_confidence REAL,
        plan_action TEXT,
        plan_duration INTEGER,
        execute_action TEXT,
        execute_duration INTEGER,
        verify_reasoning TEXT,
        verify_success INTEGER,
        verify_duration INTEGER,
        heal_attempts TEXT,
        total_duration INTEGER,
        screen_state_before TEXT,
        screen_state_after TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE TABLE IF NOT EXISTS logs (
        id TEXT PRIMARY KEY,
        step_id TEXT REFERENCES steps(id) ON DELETE CASCADE,
        run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
        level TEXT NOT NULL CHECK(level IN ('debug','info','warn','error')),
        source TEXT NOT NULL CHECK(source IN ('agent','adapter','cache','planner','healer','hook','runner')),
        message TEXT NOT NULL,
        data TEXT,
        timestamp TEXT NOT NULL
      )`,
      `CREATE TABLE IF NOT EXISTS execution_logs (
        id TEXT PRIMARY KEY,
        run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
        step_id TEXT,
        type TEXT NOT NULL CHECK(type IN ('hook', 'appium-script', 'runjs')),
        name TEXT NOT NULL,
        phase TEXT NOT NULL CHECK(phase IN ('setup', 'teardown', 'inline')),
        status TEXT NOT NULL CHECK(status IN ('passed', 'failed')),
        duration INTEGER NOT NULL DEFAULT 0,
        stdout TEXT,
        stderr TEXT,
        return_data TEXT,
        variables TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        hook_id TEXT
      )`,
      `CREATE TABLE IF NOT EXISTS token_events (
        id TEXT PRIMARY KEY,
        model_name TEXT NOT NULL,
        prompt_tokens INTEGER NOT NULL DEFAULT 0,
        completion_tokens INTEGER NOT NULL DEFAULT 0,
        source TEXT NOT NULL CHECK(source IN ('test-run', 'live-editor')),
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE TABLE IF NOT EXISTS run_artifacts (
        run_id TEXT PRIMARY KEY REFERENCES runs(id) ON DELETE CASCADE,
        kind TEXT NOT NULL CHECK(kind IN ('test', 'suite-parent', 'suite-child', 'unknown')),
        schema_version INTEGER NOT NULL,
        payload TEXT NOT NULL DEFAULT '{}',
        finalized_at TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP
      )`,
      'CREATE INDEX IF NOT EXISTS idx_runs_status ON runs(status)',
      'CREATE INDEX IF NOT EXISTS idx_runs_started_at ON runs(started_at)',
      'CREATE INDEX IF NOT EXISTS idx_runs_name ON runs(name)',
      'CREATE INDEX IF NOT EXISTS idx_runs_queue ON runs(status, priority, created_at)',
      'CREATE INDEX IF NOT EXISTS idx_runs_parent ON runs(parent_run_id)',
      'CREATE INDEX IF NOT EXISTS idx_steps_run_id ON steps(run_id)',
      'CREATE INDEX IF NOT EXISTS idx_reasoning_traces_step_id ON reasoning_traces(step_id)',
      'CREATE INDEX IF NOT EXISTS idx_logs_step_id ON logs(step_id)',
      'CREATE INDEX IF NOT EXISTS idx_logs_run_id ON logs(run_id)',
      'CREATE INDEX IF NOT EXISTS idx_logs_level ON logs(level)',
      'CREATE INDEX IF NOT EXISTS idx_logs_source ON logs(source)',
      'CREATE INDEX IF NOT EXISTS idx_logs_run_level_source ON logs(run_id, level, source)',
      'CREATE INDEX IF NOT EXISTS idx_execution_logs_run_id ON execution_logs(run_id)',
      'CREATE INDEX IF NOT EXISTS idx_execution_logs_step_id ON execution_logs(step_id)',
      'CREATE INDEX IF NOT EXISTS idx_execution_logs_type ON execution_logs(type)',
      'CREATE INDEX IF NOT EXISTS idx_token_events_model ON token_events(model_name)',
      'CREATE INDEX IF NOT EXISTS idx_token_events_source ON token_events(source)',
      'CREATE INDEX IF NOT EXISTS idx_token_events_created ON token_events(created_at)',
      'CREATE INDEX IF NOT EXISTS idx_run_artifacts_kind ON run_artifacts(kind)',
      'CREATE INDEX IF NOT EXISTS idx_run_artifacts_finalized ON run_artifacts(finalized_at)',
    ],
  },
]
